version: "3"

services: 
  mongo: 
    image: mongo:latest
    ports: 
      - 27017:27017
  jupyter: 
    build: ./jupyter
    ports: 
      - 8880:8888
    volumes: 
      - ./notebooks:/home/jupyter/notebooks
      - ./datasets:/home/jupyter/datasets
    depends_on: 
      - mongo
